import{A as h,S as f,K as v,M as _,a as y,i as L}from"./assets/vendor-6e66b841.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const m of n.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function o(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(s){if(s.ep)return;s.ep=!0;const n=o(s);fetch(s.href,n)}})();document.getElementById("profile-link").addEventListener("click",function(e){e.preventDefault(),document.getElementById("profile").classList.toggle("active");const t=document.getElementById("dropdown");t.classList.contains("active")?(t.classList.remove("active"),t.style.opacity=0):(t.classList.add("active"),setTimeout(()=>{t.style.opacity=1},10))});(()=>{const e={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};e.openModalBtn.addEventListener("click",t),e.closeModalBtn.addEventListener("click",t);function t(){e.modal.classList.toggle("visually-hidden")}})();new h(".accordion-container",{openOnInit:[0],showMultiple:!0});const S=document.querySelector(".about-me-swiper-next");let w=new f(".mySwiper",{modules:[v,_],keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!0},loop:!0,slidesPerView:2,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}}});S.addEventListener("click",()=>w.slideNext());window.addEventListener("resize",()=>w.update());const B=document.querySelectorAll(".faq-accordion");B.forEach(e=>{e.addEventListener("click",()=>{e.classList.toggle("active")})});async function P(){const o="https://portfolio-js.b.goit.study/api/reviews";return(await y.get(o)).data}async function q(e){const r="https://portfolio-js.b.goit.study/api/requests";return await y.post(r,e)}const c=document.querySelector(".swiper-button-prev"),l=document.querySelector(".swiper-button-next"),p=document.querySelector(".reviews__list");document.addEventListener("DOMContentLoaded",()=>{let e;P().then(t=>{e=t.map(o=>`
      <li class="reviews__item swiper-slide">
      <img
        width="48"
        class="reviews__img"
        src="${o.avatar_url}"
        alt="${o.author}"
      />
      <h3 class="reviews__h3">${o.author}</h3>
      <p class="reviews__descr">${o.review}</p>
    </li>`).join(""),p.insertAdjacentHTML("beforeend",e)}).catch(t=>{p.insertAdjacentHTML("beforeend",'<p class="non_info">NOT FOUND</p>'),L.error({position:"topRight",message:"Sorry, there are no reviews. Please reload your page!"}),console.log(t)})});const u=new f(".swiper",{modules:[v],keyboard:{enabled:!0,onlyInViewport:!1},speed:400,spaceBetween:100,breakpoints:{768:{slidesPerView:2,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:16}}});c.addEventListener("click",()=>{u.slidePrev(),l.classList.contains("disabled_btn")&&l.classList.remove("disabled_btn")});l.addEventListener("click",()=>{u.slideNext(),c.classList.contains("disabled_btn")&&c.classList.remove("disabled_btn")});u.on("reachBeginning",()=>{c.classList.add("disabled_btn"),l.classList.remove("disabled_btn")});u.on("reachEnd",()=>{l.classList.add("disabled_btn"),c.classList.remove("disabled_btn")});const N=/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/,b=document.querySelector(".footer-form"),i=document.getElementById("user-email"),a=document.querySelector(".form-fields"),d=document.querySelector(".backdrop"),A=document.querySelector(".modal-close-btn");i.addEventListener("input",I);b.addEventListener("submit",M);A.addEventListener("click",g);document.addEventListener("keydown",e=>{e.key==="Escape"&&d.classList.remove("is-open")});d.addEventListener("click",e=>{e.target===d&&g()});function I(){N.test(i.value.trim())?(i.classList.remove("invalid"),i.classList.add("valid"),a.dataset.status="Succes!",a.style.setProperty("--status-color","#3cbc81")):(i.classList.remove("valid"),i.classList.add("invalid"),a.dataset.status="Invalid email, try again",a.style.setProperty("--status-color","#e74a3b"))}async function M(e){e.preventDefault();const t=e.target.elements.userEmail.value,o=e.target.elements.userComment.value,r={email:t.trim().toLowerCase(),comment:o.trim()};await q(r).then(()=>{E(),d.classList.add("is-open")}).catch(s=>{L.error({position:"topRight",message:"An error occurred while sending the request. Try again."})})}function g(){E(),d.classList.remove("is-open")}function E(){a.dataset.status="",i.classList.remove("valid"),b.reset()}
//# sourceMappingURL=commonHelpers.js.map
